<a href="https://colab.research.google.com/github/gfeyzakorkmaz/Tries/blob/main/Unpivoted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

path = '/content/drive/MyDrive/Dataset/complex_marketing_data_enriched.xlsx'

df = pd.read_excel(path)
df.head()

pivoted = df.pivot_table(
    values='Total Spent',
    index='Region',
    columns='Purchased Category',
    aggfunc='sum',
    fill_value=0
)

unpivoted = pivoted.reset_index().melt(
    id_vars='Region',
    var_name='Purchased Category',
    value_name='Total Spent'
)

print("\nUnpivoted Data:")
print(unpivoted)

Unpivoted Data:
   Region Purchased Category  Total Spent
0    East             Beauty          600
1   North             Beauty            0
2   South             Beauty            0
3    West             Beauty          600
4    East              Books          300
5   North              Books          800
6   South              Books            0
7    West              Books         1250
8    East           Clothing          150
9   North           Clothing            0
10  South           Clothing          750
11   West           Clothing          700
12   East        Electronics          820
13  North        Electronics          350
14  South        Electronics            0
15   West        Electronics          510
16   East         Home Goods         1300
17  North         Home Goods          790
18  South         Home Goods            0
19   West         Home Goods            0

In [6]:
df = pd.read_excel(path)
df.head()

,Customer ID,Age,Gender,Total Spent,Converted,Comments,Purchased Category,Stock,Region,Income Level,...,Campaign,Return Rate (%),Website Visit Frequency,Average Cart Value,Total Spent Diff,Spending Rank,Rolling Return Rate,High Spender,Customer Tenure Quarter,Customer Word Count
0,1,23,F,150,1,Satisfied with the service,Clothing,4,East,Medium,...,Winter Sale,2.981829,3,378.00,NaN,19.0,NaN,No,Q1,0
1,2,35,M,600,1,Needs improvement in delivery,Beauty,86,West,Low,...,Summer Sale,1.833412,6,315.52,450.0,6.0,NaN,Yes,Q3,0
2,3,45,F,800,0,Regular customer,Books,24,North,Medium,...,Black Friday,6.547401,0,250.69,200.0,1.0,3.787547,Yes,Q3,1
3,4,52,M,200,0,Occasional buyer,Beauty,10,East,Medium,...,Winter Sale,3.923717,1,222.58,-600.0,18.0,4.101510,No,Q2,0
4,5,29,F,300,1,High spender,Books,47,East,Medium,...,Winter Sale,2.306644,4,298.68,100.0,15.0,4.259254,No,Q3,0

In [9]:
import pandas as pd

path = '/content/drive/MyDrive/Dataset/complex_marketing_data_enriched.xlsx'

df = pd.read_excel(path)

customers = pd.DataFrame({
    'Customer ID',
    'Age',
    'Region'
})

spending = pd.DataFrame({
    'Customer ID',
    'Total Spent'
})

merged = pd.merge(customers, spending, on='Customer ID')
print("Merged Data:")
print(merged)

KeyError: 'Customer ID'

In [12]:
import pandas as pd

path = '/content/drive/MyDrive/Dataset/complex_marketing_data_enriched.xlsx'

df = pd.read_excel(path)


customers = pd.DataFrame(columns=['Customer ID', 'Age', 'Region'])
spending = pd.DataFrame(columns=['Customer ID', 'Total Spent'])



customers = pd.DataFrame(customers, columns=customers.columns)
spending = pd.DataFrame(spending, columns=spending.columns)

merged = pd.merge(customers, spending, on='Customer ID')
print("Merged Data:")
print(merged)

Merged Data:
Empty DataFrame
Columns: [Customer ID, Age, Region, Total Spent]
Index: []

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive